version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-{{ checksum "package.json" }}
      - run: npm run lint
  deploy:
    docker:
      - image: circleci/node:10.14
    environment:
      GIT_COMMIT_DESC: $(git log --format=%B -n 1 $CIRCLE_SHA1)
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package.json" }}
      - run: npm install
      - run: git config user.name $GITHUB_NAME
      - run: git config user.email $GITHUB_EMAIL
      - run: rm -rf docs && npm run build
      - run: cd docs && git add . && git commit -m "$GIT_COMMIT_DESC [skip ci]" && git push origin master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
