name: build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Add git worktree
        run: |
          git worktree add dist master
          mv dist/.git dist.git
      - uses: actions/setup-node@v1
      - name: Install
        run: npm ci
      - name: Build
        run: npm run generate
      - name: Deploy
        run: |
          mv dist.git dist/.git
          cd dist
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git add -A
          git commit -m "${{ github.event_name }} ${{ github.sha }}"
          git push origin master
